### ISSUE TITLE
Co-authors' names

### ISSUE THREAD

**Issue by JackWzh** [JackWzh/nuaathesis#11]
@summershrimp @cvcore @GavinLee1994 @RexSkz

模板v1.0的制作临近收官，各位给模板提供了不少建议和PR，我想把各位的名字写进模板文档中，毕竟这个模板是大家一起合作的成果。

如各位愿意提供真实姓名或允许我写上各位的名字，可以发邮件到我邮箱: zhigu1017@gmail.com中告知我；如果不愿意，也麻烦各位告知我，我只写github ID或者什么也不写就好了。

Thx~

**Comment by summershrimp** [comment]
我是可以的， 张一白。

**Comment by RexSkz** [comment]
我也可以：曾宪文。
