### ISSUE TITLE
建个交流群？ NUAATUG？

### ISSUE THREAD

**Issue by summershrimp** [JackWzh/nuaathesis#16]
ATT.

**Comment by JackWzh** [comment]
2333，虽然我毕业不在学校了不过我没意见^_^
@cvcore @GavinLee1994 @RexSkz @yzwduck

**Comment by GavinLee1994** [comment]
可以啊，我继续留校读研，估计强迫症会逼我去写研究生论文模板。有人可以讨论肯定Nice。

**Comment by seiry** [comment]
偷偷膜膜搞个群等我毕业的时候用23333

**Comment by cvcore** [comment]
用邮件列表吧

**Comment by JackWzh** [comment]
![nuaa-tug](https://user-images.githubusercontent.com/15205739/28169371-b2ced75a-6814-11e7-9e1c-dadcd0e3485a.png)

@summershrimp @cvcore @GavinLee1994 @RexSkz @yzwduck @seiry

**Comment by summershrimp** [comment]
@cvcore 并不适合中国国情。还是QQ群把

**Comment by cvcore** [comment]
@summershrimp 已加，但目前就只有我和群主 😞
