### ISSUE TITLE
中文“关键词”三个字，应为小三号而非小四号

### ISSUE THREAD

**Issue by RexSkz** [JackWzh/nuaathesis#2]
相关代码在这里：

https://github.com/JackWzh/nuaathesis/blob/master/nuaathesis.cls#L320

**Comment by JackWzh** [comment]
@RexSkz 查了下官方模板，确实是我弄错了，明天更正

**Comment by summershrimp** [comment]
@RexSkz 增老师你咋不直接发mr。。

**Comment by RexSkz** [comment]
@summershrimp 忘了。。有了再发😂
