### ISSUE TITLE
给模板添加查重指引

### ISSUE THREAD

**Issue by JackWzh** [JackWzh/nuaathesis#4]
目前学校要求使用Word格式进行查重，所以需要将.tex源文件转换成Word

如果有使用模板同学有已经成功的方法，并愿意分享，欢迎联系本人，本人将把使用工具、方法、过程添加到本模板的说明文档中，以方便以后使用本模板的同学进行查重工作

Thx！！！

**Comment by JackWzh** [comment]
本人接下来准备使用pandoc，将.tex转换为.html再用Word 2017读入的方式进行查重尝试，后续结果将在本issue下动态更新
@summershrimp @RexSkz 欢迎二位提供查重方案

**Comment by summershrimp** [comment]
额。。我问了我们这边一个曾经管过查重的老师。说pdf也可以。。

**Comment by JackWzh** [comment]
@summershrimp 我们老师昨天去问了教务处，还没结果，知乎上说pdf查重得把参考文献拿去，貌似还有其他的注意事项，等开始查重应该就都知道了

**Comment by RexSkz** [comment]
并没想过将 pdf 转成 word 来降低重复率。不过如果真的要转的话，直接用 word 打开 pdf 文件就可以了，亲测 2013 和 2016 的转换效果跟 pdf 没有特别大的区别，如果不追求格式完美，稍微编辑一下就可以了。

P.S. 不能识别参考文献和目录的论文检测都是扯淡。

**Comment by cvcore** [comment]
我直接在毕设系统上提交的pdf版本，正在等待查重结果

**Comment by summershrimp** [comment]
知网是可以查pdf的

**Comment by RexSkz** [comment]
@summershrimp 好像十六院用的不是知网。

> 四、学院使用 “大学生论文抄袭检测专业统”（PMLC）对所有学生的毕设论文进行检查，重复度在20%以内的学生准予答辩，重复度在20%-40%的学生需修改论文重新提交检测并低于20%后准予答辩，重复度超过40%或经修改后重复度仍大于20%的学生必须延期两周修改论文并经抄袭检测合格后方可申请答辩。

http://cs.nuaa.edu.cn/?p=17734

**Comment by RexSkz** [comment]
好吧这玩意就是知网的。。。。😂

**Comment by cvcore** [comment]
貌似已经查完了，我交的晚没给查重结果直接通知答辩了。

**Comment by JackWzh** [comment]
@summershrimp @RexSkz @cvcore 在master最新的commit中添加了查重和批注指引，如果认为有能添加的内容，欢迎提PR~

**Comment by cvcore** [comment]
@JackWzh 记得更新master里的pdf模版链接

**Comment by JackWzh** [comment]
@cvcore thx，done
